name: supernova
description: Ethereum Wallet SDK in Dart.
version: 0.0.1
homepage: https://github.com/saklani/supernova

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  equatable: ^2.0.3
  rlp: ^2.0.0
  pointycastle: ^3.6.0
  nova:
    git: https://github.com/saklani/nova
  bip39: ^1.0.6
  bip32: ^2.0.0

dev_dependencies:
  test: ^1.9.0
