name: nova
description: A library to generate eth wallets, sign transaction, and send them. It also implements part of the Ethereum JSON-RPC API specification.
version: 0.0.1+2
homepage: https://github.com/saklani/nova.git

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  json_annotation: ^4.8.0
  json_rpc_2: ^3.0.1
  web_socket_channel: ^2.2.0
  rlp: ^2.0.0
  pointycastle: ^3.6.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  convert: ^3.0.2
  freezed_annotation: ^2.2.0
  meta: ^1.8.0

dev_dependencies:
  test: ^1.9.0
  async: ^2.9.0
  mockito: ^5.1.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
